### ISSUE TITLE
这个源码和这款app有什么关系么，感觉UI界面好相似

### ISSUE THREAD

**Issue by ImmortalZ** [Mixiaoxiao/Weather#1]
http://www.coolapk.com/apk/hanjie.app.pureweather

**Comment by Mixiaoxiao** [comment]
hanjie是我的朋友。
Github上有说，这个我写于2015/10，UI其实算是当时MIUI7天气和一加天气的结合体。 因为api需付费的原因没有完全成为一个可发布的app，最近整理了自己以前写的东西，就把这个扔Github了。近期还会扔一些东西到Gitbub上。

**Comment by ImmortalZ** [comment]
原来如此，感觉好强，佩服
